apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: user2
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
    kind: "KubeDirectorCluster"
spec:
  ports:
    - name: httpd-svc
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    statefulset.kubernetes.io/pod-name: httpd-svc
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
status:
  loadBalancer: {}
