apiVersion: v1
kind: Deployment
metadata:
  name: httpd
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx
      env: staging
  template:
    metadata:
      labels:
        app: nginx
        env: staging
      namespace: default
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

