apiVersion: apps/v1
kind: "KubeDirectorCluster"
kind: Deployment
metadata:
  namespace: user2
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80        
