apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user2
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: http://10.151.8.212:5000/httpd
        ports:
        - containerPort: 80        