apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 9000
        
---

apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  ports:
  - name: prime-service
    port: 80
    targetPort: 9000
  selector:
    app: httpd
type: NodePort
