apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: htpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 8086
---

kind: Service
apiVersion: v1
metadata:
  name: httpd
spec:
  type: NodePort
  ports:
    - port: 8086
      nodePort: 30000
  selector:
    name: httpd
