name: cleanup-test
on: [push]
jobs:
  check-bats-version:
    runs-on: [ self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  clean-working-directory:
    runs-on: [ self-hosted ]
    needs: check-bats-version
    steps:
      - name: Clean working directory
        shell: bash
        run: |
         cd $RUNNER_WORKSPACE
         cd ..
         rm -r *
