apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: user2
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    app: httpd
  type: NodePort
