apiVersion: v1
kind: Deployment
metadata:
  labels:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        ports:
        - containerPort: 8080
