apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user2
  name: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: ./myhttpd:latest
        ports:
        - containerPort: 80        
