apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: apache_webserve
    department: engineering
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
