apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user2
  name: httpd-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd-test
  template:
    metadata:
      labels:
        app: httpd-test
    spec:
      containers:
        - name: httpd-test
          image: ghcr.io/liavna/runtime:action_dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-githubpull

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-test-srv
  namespace: user2
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  selector:
    app: httpd-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
