apiVersion: v1
kind: Deployment
metadata:
  name: tetst
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: htpd
  template:
    metadata:
      labels:
        app: htpd
      namespace: default
    spec:
      containers:
      - env:
        - name: httpd
          value: ecp.demo
        image: httpd:latest
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
