name: local tests

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      - name: Run some commands
        id: hostss
        run: hostname
      - name: Output the commands
        run: echo "${{ steps.hostss.outputs.stdout }}"
