'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: 'docker build --tag my-image-name:httpd .'
      - name: query cluster
        uses: steebchen/kubectl@v1.0.0
        with:
          config: '${{ secrets.KUBE_CONFIG_DATA }}'
          command: get all -A
      - name: deploy to cluster
        uses: steebchen/kubectl@v1.0.0
        with:
          config: '${{ secrets.KUBE_CONFIG_DATA }}'
          command: create -f httpd.yml
