"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: "docker build --tag my-image-name:httpd ."
    - name: deploy to cluster
      uses: actions-hub/kubectl@master
      env:
       KUBE_CONFIG: ${{secrets.KUBE_CONFIG_DATA  }}
      with:
       args: apply -f httpd.yml

    
          
