on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ dev ]
name: deploy
env:
 docker_container : my-image-name:httpd
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag my-image-name:httpd
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: apply -f httpd.yml
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
    
