"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: "docker build http://10.151.8.212:5000/reg1 -t myhttpd "
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: "${{ secrets.KUBE_CONFIG_DATA }}"
        command: apply -f httpd.yml
    - name: deploy service in  cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: "${{ secrets.KUBE_CONFIG_DATA }}"
        command: apply -f httpd_service.yml
    