on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ dev ]
name: deploy
env:
 docker_container : my-image-name:$(date +%s)
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag my-image-name:$(date +%s) --output type=local
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: create deployment --image=$docker_containe http.1
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
    
      
       

      
      
      
      
      
      

